In [2]:
import json
from operator import truediv

from project_info import ROOT
import os
import pandas as pd

taxonomy_2024 = pd.read_csv(os.path.join(ROOT,"data/2024/eBird_Taxonomy_v2021.csv"))
taxonomy_2025 = pd.read_csv(os.path.join(ROOT,"data/2025/taxonomy.csv"))
print("Unique species in taxonomy.csv:", taxonomy_2025["primary_label"].nunique())

print("Unique species in 2025 data:", taxonomy_2024["SCI_NAME"].nunique())
print("Unique species in 2025 data:", taxonomy_2025["scientific_name"].nunique())

Unique species in taxonomy.csv: 206
Unique species in 2025 data: 16753
Unique species in 2025 data: 206

In [3]:
merged_df = pd.merge(
    taxonomy_2025,
    taxonomy_2024,
    left_on="scientific_name",
    right_on="SCI_NAME",
    how="left"
)
print("Unique species in 2024-2025 data:", merged_df["scientific_name"].nunique())
merged_df

Unique species in 2024-2025 data: 206

,primary_label,inat_taxon_id,scientific_name,common_name,class_name,TAXON_ORDER,CATEGORY,SPECIES_CODE,PRIMARY_COM_NAME,SCI_NAME,ORDER1,FAMILY,SPECIES_GROUP,REPORT_AS
0,1139490,1139490,Ragoniella pulchella,Ragoniella pulchella,Insecta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1192948,1192948,Oxyprora surinamensis,Oxyprora surinamensis,Insecta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1194042,1194042,Copiphora colombiae,Copiphora colombiae,Insecta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,126247,126247,Leptodactylus insularum,Spotted Foam-nest Frog,Amphibia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1346504,1346504,Neoconocephalus brachypterus,Neoconocephalus brachypterus,Insecta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,yehcar1,1432779,Milvago chimachima,Yellow-headed Caracara,Aves,11437.0,species,yehcar1,Yellow-headed Caracara,Milvago chimachima,Falconiformes,Falconidae (Falcons and Caracaras),NaN,NaN
202,yelori1,9352,Icterus nigrogularis,Yellow Oriole,Aves,32643.0,species,yelori1,Yellow Oriole,Icterus nigrogularis,Passeriformes,Icteridae (Troupials and Allies),NaN,NaN
203,yeofly1,16567,Tolmomyias sulphurescens,Yellow-olive Flycatcher,Aves,15813.0,species,yeofly1,Yellow-olive Flycatcher,Tolmomyias sulphurescens,Passeriformes,Tyrannidae (Tyrant Flycatchers),NaN,NaN
204,yercac1,10359,Cacicus cela,Yellow-rumped Cacique,Aves,32548.0,species,yercac1,Yellow-rumped Cacique,Cacicus cela,Passeriformes,Icteridae (Troupials and Allies),NaN,NaN
205,ywcpar,19003,Amazona ochrocephala,Yellow-crowned Parrot,Aves,12369.0,species,ywcpar,Yellow-crowned Parrot,Amazona ochrocephala,Psittaciformes,Psittacidae (New World and African Parrots),NaN,NaN

In [4]:
matches = pd.merge(
    taxonomy_2025,
    taxonomy_2024,
    left_on="scientific_name",
    right_on="SCI_NAME",
    how="inner"
)

print("Number of matches:", matches.shape[0])
matches

Number of matches: 146

,primary_label,inat_taxon_id,scientific_name,common_name,class_name,TAXON_ORDER,CATEGORY,SPECIES_CODE,PRIMARY_COM_NAME,SCI_NAME,ORDER1,FAMILY,SPECIES_GROUP,REPORT_AS
0,amakin1,2679,Chloroceryle amazona,Amazon Kingfisher,Aves,9788,species,amakin1,Amazon Kingfisher,Chloroceryle amazona,Coraciiformes,Alcedinidae (Kingfishers),NaN,NaN
1,amekes,4665,Falco sparverius,American Kestrel,Aves,11494,species,amekes,American Kestrel,Falco sparverius,Falconiformes,Falconidae (Falcons and Caracaras),NaN,NaN
2,ampkin1,2676,Chloroceryle aenea,American Pygmy Kingfisher,Aves,9789,species,ampkin1,American Pygmy Kingfisher,Chloroceryle aenea,Coraciiformes,Alcedinidae (Kingfishers),NaN,NaN
3,anhing,5063,Anhinga anhinga,Anhinga,Aves,7015,species,anhing,Anhinga,Anhinga anhinga,Suliformes,Anhingidae (Anhingas),Cormorants and Anhingas,NaN
4,babwar,145236,Setophaga castanea,Bay-breasted Warbler,Aves,32973,species,babwar,Bay-breasted Warbler,Setophaga castanea,Passeriformes,Parulidae (New World Warblers),NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,yehcar1,1432779,Milvago chimachima,Yellow-headed Caracara,Aves,11437,species,yehcar1,Yellow-headed Caracara,Milvago chimachima,Falconiformes,Falconidae (Falcons and Caracaras),NaN,NaN
142,yelori1,9352,Icterus nigrogularis,Yellow Oriole,Aves,32643,species,yelori1,Yellow Oriole,Icterus nigrogularis,Passeriformes,Icteridae (Troupials and Allies),NaN,NaN
143,yeofly1,16567,Tolmomyias sulphurescens,Yellow-olive Flycatcher,Aves,15813,species,yeofly1,Yellow-olive Flycatcher,Tolmomyias sulphurescens,Passeriformes,Tyrannidae (Tyrant Flycatchers),NaN,NaN
144,yercac1,10359,Cacicus cela,Yellow-rumped Cacique,Aves,32548,species,yercac1,Yellow-rumped Cacique,Cacicus cela,Passeriformes,Icteridae (Troupials and Allies),NaN,NaN
145,ywcpar,19003,Amazona ochrocephala,Yellow-crowned Parrot,Aves,12369,species,ywcpar,Yellow-crowned Parrot,Amazona ochrocephala,Psittaciformes,Psittacidae (New World and African Parrots),NaN,NaN

It appears thatt the vast majority of species are present in both datasets.

In [5]:
species_2024 = dict(zip(matches["SPECIES_CODE"],matches["PRIMARY_COM_NAME"]))
species_2025 = dict(zip(matches["inat_taxon_id"],matches["common_name"]))
print("Species in 2024:", len(species_2024.keys()))
print("Species in 2025:", len(species_2025.keys()))

Species in 2024: 146
Species in 2025: 146

In [6]:
df_2024 = pd.read_csv("../data/2024/train_metadata.csv")
df_2025 = pd.read_csv("../data/2025/train.csv")
df_2024.shape, df_2025.shape

((24459, 12), (28564, 13))

In [7]:
df_2024['filename'] = df_2024['filename'].apply(lambda x: f"2024/train_audio/{x}")
df_2025['filename'] = df_2025['filename'].apply(lambda x: f"2025/train_audio/{x}")

In [8]:
#  common_name, filename
merged_df =  pd.concat([df_2024, df_2025])
merged_df.shape

(53023, 13)

In [9]:
merged_df.drop_duplicates().shape

(53023, 13)

In [10]:
print(merged_df['url'].nunique())
print(merged_df['filename'].nunique())

52970
53023

In [11]:
merged_df.head()

,primary_label,secondary_labels,type,latitude,longitude,scientific_name,common_name,author,license,rating,url,filename,collection
0,asbfly,[],['call'],39.2297,118.1987,Muscicapa dauurica,Asian Brown Flycatcher,Matt Slaymaker,Creative Commons Attribution-NonCommercial-Sha...,5.0,https://www.xeno-canto.org/134896,2024/train_audio/asbfly/XC134896.ogg,NaN
1,asbfly,[],['song'],51.4030,104.6401,Muscicapa dauurica,Asian Brown Flycatcher,Magnus Hellström,Creative Commons Attribution-NonCommercial-Sha...,2.5,https://www.xeno-canto.org/164848,2024/train_audio/asbfly/XC164848.ogg,NaN
2,asbfly,[],['song'],36.3319,127.3555,Muscicapa dauurica,Asian Brown Flycatcher,Stuart Fisher,Creative Commons Attribution-NonCommercial-Sha...,2.5,https://www.xeno-canto.org/175797,2024/train_audio/asbfly/XC175797.ogg,NaN
3,asbfly,[],['call'],21.1697,70.6005,Muscicapa dauurica,Asian Brown Flycatcher,vir joshi,Creative Commons Attribution-NonCommercial-Sha...,4.0,https://www.xeno-canto.org/207738,2024/train_audio/asbfly/XC207738.ogg,NaN
4,asbfly,[],['call'],15.5442,73.7733,Muscicapa dauurica,Asian Brown Flycatcher,Albert Lastukhin & Sergei Karpeev,Creative Commons Attribution-NonCommercial-Sha...,4.0,https://www.xeno-canto.org/209218,2024/train_audio/asbfly/XC209218.ogg,NaN

In [12]:
import random

def generate_random_color():
    return '#{:06x}'.format(random.randint(0, 0xFFFFFF))

In [13]:
s = """<View>
  <Labels name="label" toName="audio" zoom="true" hotkey="ctrl+enter">\n """
for common_name in merged_df['common_name'].unique():
    s+=f'<Label value="{common_name}" background="{generate_random_color()}"/>\n'
s+="""
    </Labels>
  <Audio name="audio" value="$audio"/>
</View>"""

In [14]:
with open(os.path.join(ROOT,"ls_taxonomy.txt"), "w") as f:
    f.write(s)

In [15]:
import os

print(os.listdir("/"))

['var', 'srv', 'dev', 'mnt', 'lib32', 'etc', 'root', 'home', 'tmp', 'sys', 'libx32', 'lib64', 'swapfile', 'bin', 'snap', 'run', 'opt', 'lost+found', 'cdrom', 'lib', 'media', 'boot', 'usr', 'sbin', 'proc']

In [16]:
import json
template = json.load(open(os.path.join(ROOT,"difference.json")))
#json.dump(template, open(os.path.join(ROOT,"difference_i.json"), "w"), indent=6)
template = json.load(open(os.path.join(ROOT,"difference_i.json")))

In [17]:
merged_df.common_name.unique()

array(['Asian Brown Flycatcher', 'Ashy Drongo', 'Ashy Prinia',
       'Ashy Woodswallow', 'Asian Koel', 'Asian Openbill',
       'Indian Paradise-Flycatcher', 'Asian Palm-Swift',
       'Black-and-orange Flycatcher', 'Barn Swallow',
       'Black-crowned Night-Heron', 'Flame-throated Bulbul',
       'Black-rumped Flameback', 'Black-winged Kite',
       'Black-winged Stilt', 'Black Drongo', 'Black Eagle', 'Black Kite',
       'Black-hooded Oriole', 'Black-naped Monarch',
       "Blyth's Reed Warbler", 'Brown-capped Pygmy Woodpecker',
       'Brahminy Kite', 'Brahminy Starling', 'Brown-cheeked Fulvetta',
       'Brown Fish-Owl', 'Brown Boobook', 'Brown Shrike',
       'Bronzed Drongo', 'Bronze-winged Jacana', 'Brown Wood-Owl',
       'Blue-tailed Bee-eater', 'Bar-winged Flycatcher-shrike',
       'Cattle Egret', 'Chestnut-headed Bee-eater', 'Common Hawk-Cuckoo',
       'Common Flameback', 'Common Greenshank', 'Common Iora',
       'Common Kingfisher', 'Eurasian Moorhen', 'Common Myna',
       'Indian Peafowl', 'Common Rosefinch', 'Common Sandpiper',
       'Common Tailorbird', 'Coppersmith Barbet',
       'Crimson-backed Sunbird', 'Crested Goshawk', 'Malabar Barbet',
       'Crested Serpent-Eagle', 'Dark-fronted Babbler', 'Oriental Darter',
       'Western Yellow Wagtail', 'Asian Emerald Dove',
       'Eurasian Collared-Dove', 'Indian Blackbird', 'Eurasian Coot',
       'Forest Wagtail', 'Garganey', 'Glossy Ibis',
       'Golden-fronted Leafbird', 'Gray Heron', 'Green Bee-eater',
       'Greater Coucal', 'Great Egret', 'Greater Flameback',
       'Great Hornbill', 'Gray Junglefowl', 'Great Eared-Nightjar',
       'Greenish Warbler', 'Green Sandpiper', 'Green Warbler',
       'Greater Racket-tailed Drongo', 'Gray Francolin',
       'Jungle Nightjar', 'Gray Wagtail', 'Gray-breasted Prinia',
       'Gray-headed Canary-Flycatcher', 'Heart-spotted Woodpecker',
       'Eurasian Hoopoe', 'House Crow', 'House Sparrow',
       'Indian Blue Robin', 'Indian Pitta', 'Indian Robin',
       'Indian Roller', 'Indian Yellow Tit', 'Indian Golden Oriole',
       'Indian Pond-Heron', 'Indian Scimitar-Babbler', 'Indian Scops-Owl',
       'Intermediate Egret', 'Indian Spot-billed Duck',
       "Jerdon's Bushlark", 'Jungle Babbler', 'Jungle Myna',
       'Jungle Owlet', 'Kentish Plover', 'Palani Laughingthrush',
       'Large-billed Crow', 'Laughing Dove', 'Large-billed Leaf Warbler',
       'Lesser Yellownape', 'Lesser Whistling-Duck',
       'Little Ringed Plover', 'Little Egret', 'Little Grebe',
       'Little Spiderhunter', 'Little Swift', "Loten's Sunbird",
       'Malabar Gray Hornbill', 'Malabar Parakeet', 'Malabar Trogon',
       'Malabar Woodshrike', 'Marsh Sandpiper',
       'Malabar Whistling-Thrush', 'Mountain Imperial-Pigeon',
       'Nilgiri Flycatcher', 'Nilgiri Wood-Pigeon',
       'Scaly-breasted Munia', 'Oriental Honey-buzzard',
       'Paddyfield Pipit', 'Pale-billed Flowerpecker', 'Painted Stork',
       'Pied Bushchat', 'Pied Kingfisher', 'Gray-bellied Cuckoo',
       'Nilgiri Flowerpecker', 'Plain Prinia', 'Plum-headed Parakeet',
       'Gray-fronted Green-Pigeon', 'Purple Heron',
       'Purple-rumped Sunbird', 'Purple Sunbird', 'Gray-headed Swamphen',
       'Puff-throated Babbler', 'Red Spurfowl', 'Red-rumped Swallow',
       'Red-vented Bulbul', 'Red-whiskered Bulbul', 'Red-wattled Lapwing',
       'Rock Pigeon', 'Rose-ringed Parakeet', 'Rosy Starling',
       'Rufous Babbler', 'Rufous Treepie', 'Rufous Woodpecker',
       'Rusty-tailed Flycatcher', 'Spot-bellied Eagle-Owl',
       'Orange Minivet', 'Shikra', 'Small Minivet', 'Southern Hill Myna',
       'Speckled Piculet', 'Spotted Dove', 'Spotted Owlet',
       'Square-tailed Bulbul', 'Stork-billed Kingfisher',
       'Streak-throated Woodpecker', 'Thick-billed Warbler',
       "Tickell's Blue Flycatcher", "Tickell's Leaf Warbler",
       'Velvet-fronted Nuthatch', 'Vernal Hanging-Parrot',
       'White-bellied Blue Flycatcher', 'Eurasian Marsh-Harrier',
       'White-browed Bulbul', 'White-bellied Sholakili',
       'White-bellied Treepie', 'White-browed Wagtail',
       'White-breasted Waterhen', 'White-bellied Woodpecker',
       'White-cheeked Barbet', 'Whiskered Tern', 'White-rumped Munia',
       'White-throated Kingfisher', 'Wood Sandpiper',
       'Wayanad Laughingthrush', 'Yellow-billed Babbler',
       'Yellow-browed Bulbul', 'Zitting Cisticola',
       'Ragoniella pulchella', 'Oxyprora surinamensis',
       'Copiphora colombiae', 'Spotted Foam-nest Frog',
       'Neoconocephalus brachypterus', 'Emerald Glass Frog',
       'Andean Poison Frog', 'Cocconotus aratifrons',
       'Docidocercus fasciatus', 'Daedadelus waehnerorum ',
       'Common Rocket Frog', 'Yellow-striped Poison Dart Frog',
       'Spotted-thighed Poison Frog', 'Lesser Antillean whistling frog',
       'Whistling Grass Frog', 'Mexican White-lipped Frog',
       'Masked Tree Frog', 'Caracas Snouted Tree Frog',
       'Red Snouted Tree Frog', 'Common Raccoon',
       'Neotropical River Otter', 'Jaguar', 'Mountain Lion',
       'Crab-eating Fox', 'Collared Peccary', 'Red-tailed Squirrel',
       'Brown-throated Three-toed Sloth', 'Colombian Plump Frog',
       'Panama Humming Frog', 'Katydids', 'Typical Cicadas', 'Giant Toad',
       'Eschatoceras bipunctatus', 'Orophus conspersus', 'True Crickets',
       'Copiphora gracilis', 'Rusty Tree Frog',
       'Chirique-Flusse Tree Frog', 'Colombian Red Howler Monkey',
       'Colombian Niputidea Nurse Frog', "Bogert's Aquatic Tree Frog",
       "Boettger's Colombian Tree Frog", 'Harlequin Treefrog',
       'Yellow Tree Frog', 'Esmereldas Robber Frog', 'Túngara Frog',
       "Tatayo's Glass Frog", "Savage's Thin-toed Frog",
       "Vaillant's Frog", 'Cachabi Robber Frog', 'Bogota Robber Frog',
       'Banded Rain Frog', 'Palm Rocket Frog', 'Veined Tree Frog',
       'Panoploscelis specularis', 'Copris susanae',
       'Santa Rita Rocket Frog', "Rivero's Toad", 'Typophyllum inflatum',
       'Subria sylvestris', 'Amazon Kingfisher', 'American Kestrel',
       'American Pygmy Kingfisher', 'Anhinga', 'Bay-breasted Warbler',
       'Bare-faced Ibis', 'Bananaquit', 'Blue-and-yellow Macaw',
       'Black-bellied Whistling-Duck', 'Bicolored Wren',
       'Black-capped Donacobius', 'Yellow-throated Toucan',
       'Blue-black Grassquit', 'Black-bellied Wren',
       'Black-crested Antshrike', 'Black-collared Hawk',
       'Black-chested Jay', 'Black-crowned Tityra', 'Blue-headed Parrot',
       'Black Vulture', 'Boat-billed Flycatcher', 'Boat-billed Heron',
       'Brown-throated Parakeet', 'Blue-billed Curassow',
       'Buff-breasted Wren', 'Whooping Motmot', 'Blue-gray Tanager',
       'Buff-throated Saltator', 'Carib Grackle', 'Cattle Tyrant',
       'Chestnut-backed Antbird', 'Chestnut-fronted Macaw',
       'Cinnamon Becard', 'Cocoi Heron', 'Cocoa Woodcreeper',
       'Collared Aracari', 'Colombian Chachalaca', 'Common Pauraque',
       'Common Potoo', 'Common Tody-Flycatcher', 'Crimson-backed Tanager',
       'Crimson-crested Woodpecker', 'Crested Bobwhite', 'Crested Guan',
       'Crested Oropendola', 'Eared Dove', 'Fork-tailed Flycatcher',
       'Golden-headed Manakin', 'Olivaceous Saltator', 'Great Black Hawk',
       'Greater Ani', 'Green Ibis', 'Great Kiskadee', 'Great Potoo',
       'Great Tinamou', 'Green Kingfisher', 'Gray Seedeater',
       'Gray-breasted Martin', 'Gray-cowled Wood-Rail',
       'Large-billed Tern', 'Laughing Falcon', 'Least Grebe',
       'Lineated Woodpecker', 'Little Tinamou', 'Masked Tityra',
       'Neotropic Cormorant', 'Northern Screamer', 'Olivaceous Piculet',
       'Orange-chinned Parakeet', 'Pale-legged Hornero', 'Palm Tanager',
       'Pale-vented Pigeon', 'Pied Puffbird', 'Piratic Flycatcher',
       'Pied Water-Tyrant', 'Plain-brown Woodcreeper',
       'Plain-colored Tanager', 'Plumbeous Kite', 'Purple Gallinule',
       'Red-and-green Macaw', 'Red-breasted Meadowlark',
       'Red-crowned Woodpecker', 'Ringed Kingfisher', 'Roadside Hawk',
       'Roseate Spoonbill', 'Royal Flycatcher',
       'Rufous-tailed Hummingbird', 'Ruddy-breasted Seedeater',
       'Rufous Motmot', 'Ruddy Ground Dove', 'Rusty-margined Flycatcher',
       'Rufescent Tiger-Heron', 'Rufous-tailed Jacamar',
       'Russet-throated Puffbird', 'Saffron Finch',
       'Saffron-headed Parrot', 'Savanna Hawk', 'Sepia-capped Flycatcher',
       'Shining-green Hummingbird', 'Slate-headed Tody-Flycatcher',
       'Smooth-billed Ani', 'Snowy Egret',
       'Southern Beardless-Tyrannulet', 'Social Flycatcher',
       'Solitary Sandpiper', 'Southern Lapwing',
       'Spot-breasted Woodpecker', 'Spectacled Owl',
       'Spectacled Parrotlet', 'Southern Rough-winged Swallow',
       'Straight-billed Woodcreeper', 'Striped Cuckoo',
       'Streaked Flycatcher', 'Striated Heron', 'Striped Owl',
       'Thick-billed Seed-Finch', 'Thick-billed Euphonia',
       'Brown-winged Schiffornis', 'Tropical Kingbird', 'Tropical Parula',
       'Tropical Screech-Owl', 'Turkey Vulture', 'Vermilion Flycatcher',
       'Wattled Jacana', 'White-breasted Wood-Wren',
       'White-bellied Antbird', 'White-bearded Manakin',
       'White-fringed Antwren', 'White-headed Marsh Tyrant',
       'White-tipped Dove', 'White-tailed Trogon', 'White-winged Swallow',
       'Wood Stork', 'Crested Caracara', 'Yellow-bellied Elaenia',
       'Yellow-breasted Flycatcher', 'Yellow-bellied Seedeater',
       'Yellow-chinned Spinetail', 'Yellow-crowned Tyrannulet',
       'Yellow-hooded Blackbird', 'Yellow-headed Caracara',
       'Yellow Oriole', 'Yellow-olive Flycatcher',
       'Yellow-rumped Cacique', 'Yellow-crowned Parrot'], dtype=object)

In [18]:
import copy
from mutagen.oggvorbis import OggVorbis

output = []
for idx, row in merged_df.iterrows():
    audio = OggVorbis(os.path.join(ROOT,"data",row.filename))
    duration_seconds = audio.info.length
    tmp = copy.deepcopy(template[0])
    tmp["id"] = idx
    tmp["annotations"][0]["result"][0]["original_length"] = duration_seconds
    tmp["annotations"][0]["result"][0]["value"]["start"] = 0
    tmp["annotations"][0]["result"][0]["value"]["end"] = duration_seconds
    tmp["annotations"][0]["result"][0]["value"]["labels"] = [row.common_name]
    tmp["annotations"][0]["ground_truth"] = True
    tmp["annotations"][0]["task"] = idx
    tmp["data"]["audio"] = "/data/local-files/?d=data/datasets/data_"+row.filename
    output.append(tmp)
    #if idx == 10: break
json.dump(output, open(os.path.join(ROOT,"ls_complete_local_clean.json"), "w"), indent=6)

'import copy\nfrom mutagen.oggvorbis import OggVorbis\n\noutput = []\nfor idx, row in merged_df.iterrows():\n    audio = OggVorbis(os.path.join(ROOT,"data",row.filename))\n    duration_seconds = audio.info.length\n    tmp = copy.deepcopy(template[0])\n    tmp["id"] = idx\n    tmp["annotations"][0]["result"][0]["original_length"] = duration_seconds\n    tmp["annotations"][0]["result"][0]["value"]["start"] = 0\n    tmp["annotations"][0]["result"][0]["value"]["end"] = duration_seconds\n    tmp["annotations"][0]["result"][0]["value"]["labels"] = [row.common_name]\n    tmp["annotations"][0]["ground_truth"] = True\n    tmp["annotations"][0]["task"] = idx\n    tmp["data"]["audio"] = "/data/local-files/?d=data/datasets/data_"+row.filename\n    output.append(tmp)\n    #if idx == 10: break\njson.dump(output, open(os.path.join(ROOT,"ls_complete_local_clean.json"), "w"), indent=6)'